name: Compile Project
on:
  release:
    types:
      - created
  push:
  pull_request:

permissions:
  contents: write
  id-token: write
  pages: write
  packages: write

jobs:
  compile:
    strategy:
      matrix:
        # 16 is current
        # 20 is in testing
        node-version: [16.x, 20.x]
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: pnpm/action-setup@v4.1.0
        with:
          version: 9
          run_install: false
          standalone: true
      - uses: actions/setup-node@v4.1.0
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm
      - run: pnpm install
      - run: pnpm build
      - uses: actions/upload-artifact@v4.6.0
        with:
          name: ${{ github.event.repository.name }}.${{ matrix.node-version }}
          path: dist
          if-no-files-found: error
